# ------- Stage 1: Build ----------

From maven:3.9.6-eclipse-temurin-21 AS builder

WORKDIR /build

COPY pom.xml .
Run mvn dependency:go-offline


COPY src ./src
RUN mvn clean package -DskipTests


# ----------------step-2 : Runtime-----------
 # this jre jammy is image is less how ever we have even
 # lesser than that so i can reduce my image size

  #  From eclipse-temurin:21-jre-jammy   - with this my image size is 305mb

 # with this jre alpine my image size is 227mb
 # --> From eclipse-temurin:21-jre-alpine

# this distoless jre will reduce my image size in 211mb
From gcr.io/distroless/java21-debian12

WORKDIR /app

COPY --from=builder /build/target/*.jar app.jar

EXPOSE 8084

ENTRYPOINT ["java", "-jar","app.jar"]

