# -------------dependency layer --------

From maven:3.9.6-eclipse-temurin-21 AS deps
WORKDIR /build
COPY pom.xml .
Run mvn -B dependency:go-offline

#----------------Build layer ---------
From maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /build
COPY --from=deps /root/.m2 /root/.m2
COPY pom.xml .
COPY src ./src
RUN mvn -B clean package -DskipTests


#--------------Runtime-------------
From gcr.io/distroless/java21-debian12
WORKDIR /app

# create a user
Run  useradd -m nonroot

COPY --from=builder /build/target/*.jar app.jar
EXPOSE 8084

#this line will make sure to run in nonroot
# if we dont mention it will run in /root i cause security isseu
USER nonroot
ENTRYPOINT ["java", "-jar", "app.jar"]