FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker.io wget && \
    wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb && \
    dpkg -i trivy_0.50.0_Linux-64bit.deb || apt-get install -f -y && \
    curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/
